# -*- coding: utf-8 -*-
"""flotta_aziendale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/messinesetsrm-cell/67aa676a108d59860cf39cd72c02f021/flotta_aziendale.ipynb
"""

import pandas as pd
from datetime import datetime
import streamlit as st
import pandas as pd

FILE_PRINCIPALE = "flotta.xlsx"
FILE_STORICO = "storico_assegnazioni.xlsx"

def registra_riassegnazione(targa_input, nuovo_operatore):
    # Carichiamo il database attuale
    df_p = pd.read_excel(FILE_PRINCIPALE)

    # Pulizia nomi colonne per sicurezza (toglie spazi extra)
    df_p.columns = df_p.columns.str.strip()

    # Cerchiamo la targa
    if targa_input in df_p['Targa'].values:
        idx = df_p.index[df_p['Targa'] == targa_input][0]

        # Recuperiamo i dati per lo storico prima di sovrascriverli
        vecchio_op = df_p.at[idx, 'Operatore']
        data_inizio = df_p.at[idx, 'Data_Assegnazione']
        data_fine = datetime.now().strftime("%Y-%m-%d")

        # --- PREPARAZIONE STORICO ---
        # Nota: Ho rimosso il riferimento a 'Tipo' che non esiste nel tuo file principale
        nuova_riga_storico = {
            "Targa": [targa_input],
            "Operatore": [vecchio_op],
            "Inizio_Assegnazione": [data_inizio],
            "Fine_Assegnazione": [data_fine],
            "Tipo_Vettura": ["N/D"] # Dato che non c'è nel file principale, mettiamo non disponibile
        }
        df_new_st = pd.DataFrame(nuova_riga_storico)

        try:
            df_st_esistente = pd.read_excel(FILE_STORICO)
            df_finale_st = pd.concat([df_st_esistente, df_new_st], ignore_index=True)
        except:
            df_finale_st = df_new_st

        # Salviamo lo storico
        df_finale_st.to_excel(FILE_STORICO, index=False)

        # --- AGGIORNAMENTO PRINCIPALE ---
        df_p.at[idx, 'Operatore'] = nuovo_operatore
        df_p.at[idx, 'Data_Assegnazione'] = data_fine
        df_p.to_excel(FILE_PRINCIPALE, index=False)

        print(f"✅ Riassegnazione completata per {targa_input}")
        print(f"Storico: {vecchio_op} -> {nuovo_operatore}")
    else:
        print(f"❌ Errore: Targa {targa_input} non trovata.")

# Esecuzione
targa = input("Inserisci Targa: ").strip().upper()
nuovo = input("Inserisci Nuovo Operatore: ").strip().upper()
registra_riassegnazione(targa, nuovo)
